name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.1.0
  image_pickers: ^2.0.6
  cloudinary_public: ^0.23.1
  pdf: ^3.11.3
  printing: ^5.11.0
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  image_picker: ^1.2.1
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logoNgoet.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/